name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Revisar el codigo del repositorio
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
